---
# tasks file for roles/database

    - name: Create a database container
      docker_container:
        name: database
        image: jeremythorouss/tp-devops-epf-jeremy:database
        env:
          POSTGRES_PASSWORD=pwd
          POSTGRES_USER=usr
          POSTGRES_DB=db
        networks:
          - name: "app-network"